language: csharp
solution: SeleniumExtensions.sln
install:
  - nuget restore SeleniumExtensions.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
  script:
  - xbuild /p:Configuration=Release SeleniumExtensions.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SeleniumExtensions.Tests/bin/Release/MyProject.Tests.dll